name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_TAG: hellohair-quizz
  REPOSITORY: codeinsight

jobs:

  loginCreds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - shell: bash
        run: |
          TOKEN=$(echo ${DOCKER_USERNAME}:${DOCKER_PASSWORD} | base64 -w 0)
          echo "{ \"auths\": { \"registry.hub.docker.com\": { \"auth\": \"${TOKEN}\" } }  }  }" >> .docker/config.json
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: config
          path: |
            .docker/config.json

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t "$IMAGE_TAG" -f ./devops/docker/Dockerfile ./

  # login:
  #   runs-on: ubuntu-latest
  #   environment: production
  #   steps:
  #     - uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME  }}
  #         password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
  push:
    needs: login
    runs-on: ubuntu-latest
    steps: 
    - name: Download dockerhub auth credentials
      uses: actions/download-artifact@v3
      with:
        name: config
    - name: Print auth config
      shell: bash
      run: |
        value=`cat config.json`
        echo The result is $value
    # - uses: actions/checkout@v3
    # - name: Push docker image to dockerhub
    #   run: docker push sevosevo/$REPOSITORY:$IMAGE_TAG