name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_TAG: hellohair-quizz
  REPOSITORY: sevosevo/codeinsight

jobs:

  docker_login:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - shell: bash
        run: |
          echo "${DOCKER_USERNAME}:${DOCKER_PASSWORD}"
          TOKEN=$(echo "${DOCKER_USERNAME}:${DOCKER_PASSWORD}" | base64 -w 0)
          echo "{ \"auths\": { \"registry.hub.docker.com\": { \"auth\": \"${TOKEN}\" } }  }  }" >> config.json
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: config
          path: |
            config.json

  # build:
  #   needs: login_creds
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Build the Docker image
  #     run: docker build -t "$IMAGE_TAG" -f ./devops/docker/Dockerfile ./

  # login:
  #   runs-on: ubuntu-latest
  #   environment: production
  #   steps:
  #     - uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME  }}
  #         password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
  build_and_push:
    needs: [docker_login]
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    # - name: Build the Docker image
    #   run: docker build -t "$IMAGE_TAG" -f ./devops/docker/Dockerfile ./
    - name: Pull docker credentials artifacts
      uses: actions/download-artifact@v3
      with:
        name: config
    - name: Push docker image
      shell: bash
      run: |
        DOCKER_AUTH_CONFIG=`cat config.json`
        echo $DOCKER_AUTH_CONFIG > ~/.docker/config.json
        echo $(cat ~/.docker/config.json)
        docker tag $IMAGE_TAG $REPOSITORY:$IMAGE_TAG
        docker push $REPOSITORY:$IMAGE_TAG
    # - uses: actions/checkout@v3
    # - name: Push docker image to dockerhub
    #   run: docker push sevosevo/$REPOSITORY:$IMAGE_TAG