name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GCLOUD_REGISTRY: gcr.io
  IMAGE_TAG: v1
  IMAGE_NAME: hellohairquizz
  SERVICE_NAME: hellohairquizz
  REGION: europe-west9

jobs:
  Build_Push_And_Deploy_To_GCloud:
    environment: production
    runs-on: ubuntu-latest
#    env:
#        IMAGE_URL: gcr.io/${{ vars.GCLOUD_PROJECT_ID }}/hellohair-quizz
    steps:
      - uses: actions/checkout@v3

      - id: 'auth'
        uses: google-github-actions/auth@v1.1.1
        with:
          credentials_json: '${{ vars.GCLOUD_KEY_FILE_CONTENT }}'

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v1.1.1

      - name: Build/Push docker image to gcloud registry
        run: |
          gcloud builds submit --tag "$GCLOUD_REGISTRY/${{ vars.GCLOUD_PROJECT_ID }}/${{ vars.GCLOUD_REGISTRY_REPOSITORY }}/$IMAGE_NAME:$IMAGE_TAG" ./

      - name: Deploy image
        run: |
          gcloud run deploy $SERVICE_NAME --image "$GCLOUD_REGISTRY/${{ vars.GCLOUD_PROJECT_ID }}/${{ vars.GCLOUD_REGISTRY_REPOSITORY }}/$IMAGE_NAME:$IMAGE_TAG" --region $REGION