name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_TAG: hellohair-quizz
  REPOSITORY: sevosevo/codeinsight

jobs:

  build_and_push:
    environment: production
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
        docker build -t "$IMAGE_TAG" -f ./devops/docker/Dockerfile ./
        docker tag $IMAGE_TAG $REPOSITORY:$IMAGE_TAG
